name: Kjør dagsrutine
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' 
jobs:
  daglig-kjoring:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      LAGSERIEN_DB_PSW: ${{ secrets.LAGSERIEN_DB_PSW }}
    steps:
      - name: Sjekk ut repository
        uses: actions/checkout@v3
      
      - name: Oppsett Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer avhengigheter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Kjører stevnekontroll
        run: |
          python bin/kjør_stevnekontroll.py ${{ secrets.LAGSERIEN_SERIEAR }}
          EXIT_CODE=$?
          if [ $EXIT_CODE -ne 0 ]; then
            echo "::warning::The command failed with exit code $EXIT_CODE"
          fi
          exit 0  # Ensure the step still passes

      - name: Kjører serieuttrekk
        run: python bin/kjør_serieuttrekk.py ${{ secrets.LAGSERIEN_SERIEAR }}
        
      - name: Kjører serietildeling
        run: python bin/kjør_serieutdeling.py ${{ secrets.LAGSERIEN_SERIEAR }}
        
      - name: Kjører seriekalkulator
        run: python bin/kjør_seriekalkulator.py ${{ secrets.LAGSERIEN_SERIEAR }}
